- name: mnt folder
  file:
    path: /mnt
    state: directory
    owner: solana
    group: solana
    mode: "0777"
  become: true
  become_user: root

- name: solana snapshots
  file:
    path: /{{ snapshots_path }}
    state: directory
    owner: {{ user }}
    group: {{ user }}
  become: true
  become_user: root

- name: solana ledger
  file:
    path: /{{ ledger_path }}
    state: directory
    owner: {{ user }}
    group: {{ user }}
  become: true
  become_user: root

- name: solana accounts
  file:
    path: /{{ accounts_path }}
    state: directory
    owner: {{ user }}
    group: {{ user }}
  become: true
  become_user: root

- name: solana logs
  become: true
  become_user: root
  file:
    path: /mnt/logs
    state: directory
    owner: {{ user }}
    group: {{ user }}
