- name: validator setup
  become: true
  become_user: '{{ user }}'
  copy:
    src: validator.sh
    dest: '/home/{{ user }}/validator.sh'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: "0755"
    
- name: replace user var in validator.sh
  ansible.builtin.replace:
    path: '/home/{{ user }}/validator.sh'
    regexp: '%user%'
    replace: '{{ user }}'
    
- name: replace ledger_path var in validator.sh
  ansible.builtin.replace:
    path: '/home/{{ user }}/validator.sh'
    regexp: '%ledger_path%'
    replace: '{{ ledger_path }}'

- name: replace snapshots_path var in validator.sh
  ansible.builtin.replace:
    path: '/home/{{ user }}/validator.sh'
    regexp: '%snapshots_path%'
    replace: '{{ snapshots_path }}'
    
- name: replace accounts_path var in validator.sh
  ansible.builtin.replace:
    path: '/home/{{ user }}/validator.sh'
    regexp: '%accounts_path%'
    replace: '{{ accounts_path }}'

- name: setup sol.service
  become: true
  become_user: root
  copy:
    src: sol.service
    dest: /etc/systemd/system/sol.service
    owner: root
    group: root
    mode: "0755"

- name: replace user var in sol.service
  ansible.builtin.replace:
    path: /etc/systemd/system/sol.service
    regexp: '%user%'
    replace: '{{ user }}'

- name: copy restart.sh
  become: true
  become_user: '{{ user }}'
  copy:
    src: restart.sh
    dest: '/home/{{ user }}/restart.sh'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: "0755"

