- name: validator setup
  become: true
  become_user: '{{ user }}'
  copy:
    src: validator.sh
    dest: '/home/{{ user }}/validator.sh'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: "0755"

- name: setup sol.service
  become: true
  become_user: root
  copy:
    src: sol.service
    dest: /etc/systemd/system/sol.service
    owner: root
    group: root
    mode: "0755"

- name: copy restart.sh
  become: true
  become_user: '{{ user }}'
  copy:
    src: restart.sh
    dest: '/home/{{ user }}/restart.sh'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: "0755"
    
- name: copy download_start.sh
  become: true
  become_user: '{{ user }}'
  copy:
    src: download_start.sh
    dest: '/home/{{ user }}/download_start.sh'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: "0755"

- name: copy snapcheck.py
  become: true
  become_user: '{{ user }}'
  copy:
    src: snapcheck.py
    dest: /mnt/snapcheck.py
    owner: '{{ user }}'
    group: '{{ user }}'

- name: copy snapshot-finder.py
  become: true
  become_user: '{{ user }}'
  copy:
    src: snapshot-finder.py
    dest: /mnt/snapshot-finder.py
    owner: '{{ user }}'
    group: '{{ user }}'

- name: copy montip.py
  become: true
  become_user: '{{ user }}'
  copy:
    src: montip.py
    dest: /mnt/montip.py
    owner: '{{ user }}'
    group: '{{ user }}'

