- name: solana repository
  become: true
  become_user: solana
  git:
    repo: 'https://github.com/jito-foundation/jito-solana.git'
    dest: /mnt/agave
    version: tags/{{ jito_version }}

- name: build solana
  become: true
  become_user: {{ user }}
  shell: source /home/{{ user }}/.cargo/env && /mnt/{{ user }}/cargo build --release
  args:
    chdir: /mnt/agave
    executable: /bin/bash