- name: '{{ user }} repo'
  become: true
  become_user: '{{ user }}'
  git:
    repo: 'https://github.com/jito-foundation/jito-solana.git'
    dest: '/mnt/{{ user }}'
    version: 'tags/{{ jito_version }}'

- name: 'build {{ user }}'
  become: true
  become_user: '{{ user }}'
  shell: 'source /home/{{ user }}/.cargo/env && /mnt/{{ user }}/cargo build --release'
  args:
    chdir: '/mnt/{{ user }}'
    executable: /bin/bash