- name: create identity key
  become: true
  become_user: {{ user }}
  shell: /mnt/{{ user }}/target/release/solana-keygen new --no-bip39-passphrase -o /home/{{ user }}/rpc_node.json
  args:
    creates: /home/{{ user }}/rpc_node.json