---
# tasks file for Solana RPC
- name: var check
  include_tasks: var_check.yaml

- name: create user
  include_tasks: user.yaml

- name: install dependencies
  include_tasks: deps.yaml

- name: folders
  include_tasks: dirs.yaml

- name: setup accounts disk
  include_tasks: disks_accounts.yaml
  when: setup_disks|default(false)|bool == true

- name: setup ledger disk
  include_tasks: disks_ledger.yaml
  when: setup_disks|default(false)|bool == true

- name: setup snapshots disk
  include_tasks: disks_snapshots.yaml
  when: setup_disks|default(false)|bool == true

- name: logrotate
  include_tasks: rotate.yaml

- name: git
  include_tasks: git.yaml

- name: solana keygen
  include_tasks: keygen.yaml

- name: file setup
  include_tasks: file_setup.yaml

- name: tune host
  include_tasks: tuner.yaml

- name: snapshot download
  include_tasks: snapshot_downloader.yaml
  when: download_snapshot|default(true)|bool == true

- name: restart without waiting
  become: true
  become_user: root
  shell: '/home/{{ user }}/restart.sh 1'
  when: download_snapshot|default(true)|bool == true

- name: restart with waiting
  become: true
  become_user: root
  shell: '/home/{{ user }}/restart.sh'
  when: download_snapshot|default(true)|bool == false
