---
# tasks file for Solana RPC
- name: var check
  include_tasks: var_check.yaml

- name: create user
  include_tasks: user.yaml

- name: install dependencies
  include_tasks: deps.yaml

- name: folders
  include_tasks: dirs.yaml

- name: logrotate
  include_tasks: rotate.yaml

- name: git
  include_tasks: git.yaml

- name: solana keygen
  include_tasks: keygen.yaml

- name: file setup
  include_tasks: file_setup.yaml

- name: tune host
  include_tasks: tuner.yaml

- name: restart without waiting
  become: true
  become_user: root
  shell: '/home/{{ user }}/restart.sh 1'
  when: default(true)|bool == true

- name: restart with waiting
  become: true
  become_user: root
  shell: '/home/{{ user }}/restart.sh'
  when: default(true)|bool == false
