- name: 'create {{ user }} group'
  become: true
  become_user: root
  group:
    name: '{{ user }}'
    state: present

- name: 'create {{ user }} user'
  become: true
  become_user: root
  user:
    name: '{{ user }}'
    create_home: yes
    groups: '{{ user }}'
    shell: /bin/bash

- name: '{{ user }} user to have passwordless sudo'
  become: true
  become_user: root
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^{{ user }}'
    line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: 'Ensure {{ user }} build is in path for {{ user }} user'
  become: true
  become_user: root
  lineinfile:
    path: '/home/{{ user }}/.bashrc'
    line: 'export PATH=/mnt/{{ user }}/target/release:$PATH'
